### ISSUE TITLE
ubuntu

### ISSUE THREAD

**Issue by loctauxphilippe** [papyros/calculator-app#3]
Can anyone give me one command to get all dependencies, clone and build process?
That'd be great!

**Comment by pierremtb** [comment]
- Download and install Qt : https://www.qt.io/download/
- Make sure you have git installed, and g++
- Then you can enter this commands : 
$ mkdir papyros
$ cd papyros
$ git clone https://github.com/papyros/qml-material
$ cd qml-material
$ qmake
$ make
$ sudo make install
$ cd ..
$ git clone https://github.com/papyros/qml-extras
$ cd qml-extras
$ qmake
$ make
$ sudo make install
$ cd ..
$ git clone https://github.com/papyros/calculator-app
$ cd calculator-app
$ qmake
$ make
$ sudo make install

Either you launch it via terminal : papyros-calculator, or you can use the desktop icon (theorically created)

Can't try it now, so please report. Happy testing !

**Comment by loctauxphilippe** [comment]
@pierremtb merci! I'll test right now! On va voir :)

**Comment by loctauxphilippe** [comment]
@pierremtb well I'm unable to get qt from qt.io, they want personal info, and I won't give them
don't you have an apt-get install command to get qt? I googled that, but nothing interesting...

**Comment by pierremtb** [comment]
@loctauxphilippe On Arch all qt packages are available, but I don't really know Ubuntu. Can't you give Qt false informations ?

**Comment by VirusKA** [comment]
^yeah you can. i told em i was 65 XD

**Comment by loctauxphilippe** [comment]
@pierremtb ok thanks! I'm on arch now, I'll just install it on arch :)
